version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-jdk-21
    container_name: jenkins-jdk-21
    privileged: true
    user: root
    restart: always
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins_home:
    name: jenkins_home
